name: "release"
concurrency: release
on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  release:
    name: "Create release"
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      timestamp: ${{ steps.get-timestamp.outputs.time }}
      release_already_exists: ${{ steps.tag_check.outputs.exists }}
      version_name: ${{ steps.generate_env_vars.outputs.tag_name }}
      version_postfix: ${{ steps.generate_env_vars.outputs.version_postfix }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Get timestamp"
        id: get-timestamp
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYYMMDDHHmm'
      - name: "Generate environmental variables"
        id: generate_env_vars
        run: |
          cargo_version=$(grep "version = " Cargo.toml | head -n 1 | sed -e "s/version = \"//" -e "s/\"//")
          version_postfix="-experimental-${{ steps.get-timestamp.outputs.time }}"
          echo "tag_name=v${cargo_version}${version_postfix}" >> $GITHUB_OUTPUT
          echo "release_name=Followers of the Midia v${cargo_version}${version_postfix}" >> $GITHUB_OUTPUT
          echo "version_postfix=${version_postfix}" >> $GITHUB_OUTPUT
      - name: "Check if there is existing git tag"
        id: tag_check
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ steps.generate_env_vars.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Push tag"
        id: push_tag
        uses: mathieudutour/github-tag-action@v5.5
        if: ${{ steps.tag_check.outputs.exists == 'false' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.generate_env_vars.outputs.tag_name }}
          tag_prefix: ""
      - name: "Create release"
        id: create_release
        uses: actions/create-release@v1
        if: ${{ steps.tag_check.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_env_vars.outputs.tag_name }}
          release_name: ${{ steps.generate_env_vars.outputs.release_name }}
          body: |
            These are the outputs for the experimental build of commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          draft: false
          prerelease: true
  build_linux:
    needs: release
    if: ${{ needs.release.outputs.release_already_exists == 'false' }}
    name: "Build (linux)"
    runs-on: ubuntu-18.04
    env:
      MIDIA_VERSION_POSTFIX: ${{ needs.release.outputs.version_postfix }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
      - name: "Install Rust toolchain"
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: "Run cargo build"
        run: |
          rustc --version
          cargo build --release
      - name: "Pack release"
        run: |
          mkdir midia_linux
          cp target/release/midia midia_linux
          chmod +x midia_linux/midia
          cat >midia_linux/midia_launcher.sh <<EOL
          #!/bin/sh
          TARGET_FILE=\$0
          cd "\$(dirname "\$TARGET_FILE")" || {
              echo "Could not change directory to '\$TARGET_FILE'" >&2
              exit 1
          }
          exec ./midia "\$@"
          EOL
          chmod +x midia_linux/midia_launcher.sh
          tar -zcf midia_linux.tar.gz midia_linux
      - name: "Upload release asset"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: midia_linux.tar.gz
          asset_name: midia-${{ needs.release.outputs.version_name }}-linux.tar.gz
          asset_content_type: application/gzip
  build_win:
    needs: release
    if: ${{ needs.release.outputs.release_already_exists == 'false' }}
    name: "Build (windows)"
    runs-on: windows-2016
    env:
      MIDIA_VERSION_POSTFIX: ${{ needs.release.outputs.version_postfix }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        shell: powershell
        run: |
          Import-Module BitsTransfer
          Start-BitsTransfer -Source "https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip" -Destination SDL2.zip
          Expand-Archive -Path SDL2.zip -Destination .
          Get-ChildItem -Path SDL2-2.0.16/lib/x64/ -Recurse -File | Move-Item -Destination . -Force
      - name: "Install Rust toolchain"
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: "Run cargo build"
        run: |
          rustc --version
          cargo build --release
      - name: "Copy folders"
        shell: bash
        run: |
          mkdir MidiaFollowers
          cp target/release/midia.exe MidiaFollowers
          cp SDL2.dll MidiaFollowers
      - name: "Pack release"
        shell: powershell
        run: |
          Compress-Archive -Path MidiaFollowers -DestinationPath midia_windows.zip
      - name: "Upload release asset"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: midia_windows.zip
          asset_name: midia-${{ needs.release.outputs.version_name }}-windows.zip
          asset_content_type: application/gzip
  build_osx:
    needs: release
    if: ${{ needs.release.outputs.release_already_exists == 'false' }}
    name: "Build (OSX)"
    runs-on: macos-10.15
    env:
      MIDIA_VERSION_POSTFIX: ${{ needs.release.outputs.version_postfix }}
    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install sdl2
          pip3 install dmgbuild
          rustup update
      - name: "Run cargo build"
        run: |
          rustc --version
          cargo build --release
      - name: "Pack release"
        run: |
          mkdir necromanzer_osx
          ls -lah target/release
#          cp target/release/necromanzer.app necromanzer_osx
#          chmod +x necromanzer_osx/necromanzer.app
#          tar -zcf necromanzer_osx.tar.gz necromanzer_osx
#      - name: "Upload release asset"
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: necromanzer_osx.tar.gz
#          asset_name: necromanzer-${{ needs.release.outputs.version_name }}-osx.tar.gz
#          asset_content_type: application/gzip
